---
nameOverride: sotallc-frontend
fullnameOverride: sotallc-frontend

deployment:
  containers:
    - name: frontend
      image:
        registry: docker.horse
        repository: vapronva/sota-llc/frontend
      ports:
        - name: http
          containerPort: 3000
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /favicon.ico
          port: http
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - unnecessary-addition

services:
  - name: sotallc-frontend
    type: ClusterIP
    ports:
      - name: http
        port: 3000
        targetPort: http
        protocol: TCP

ckic:
  enabled: true
  sites:
    - hosts:
        - sota.llc
      upstream: sotallc-frontend:3000
      robotsTag: "index, archive, nofollow"
      extraDirectives: |
        handle_path /r/* {
          redir https://cmld.ru/sota.llc{uri} permanent
        }
